import Head from "next/head";
import BadgeList from "../components/BadgeList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1 className="text-5xl text-center mt-14 font-serif mb-14">
          Badge List
        </h1>
        <BadgeList />
      </main>
    </>
  );
}
